server:
  port: 8761


spring:
  application:
    # spring-cloud 고유 ID 설정
    name: discoveryservice

eureka:
  # 이 서비스는 discovery server 역활, spring-boot 가 기동할 때 자동으로 eureka 에 client 로서 자신을 등록하려 하기에
  # 비활성 하는 설정이 필요,
  client:
    register-with-eureka: false
    fetch-registry: false